version: "3"
services:
    web:
        image: dotnetcoresqldb
        environment:
            SqlHost: db
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "MyP@ssw0rd#"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
